title: "Christopher Cadoret"
description: "Senior Business Leader | IoT & SaaS Strategy | PMP"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "corporate"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
author:
  name: "Christopher Cadoret"
  bio: "Strategic Growth & Organizational Transformation Leader."
  location: "Mundelein, IL"
  avatar: "/headshot.jpg"
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
